---

- name: Copy carbon black cloud agent 
  win_copy:
    src: "../../apps/{{ windows_servers.carbon_black_windows_agent }}"
    dest: C:\Temp\WindowsSensor.msi

- name: install carbon black cloud agent
  win_command: 'msiexec /q /i C:\Temp\WindowsSensor.msi /L* log.txt COMPANY_CODE={{ general.carbon_black_cloud_company_code }}'