---

- name: Create folder directory for AWS TA
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - /opt/splunk/etc/apps/Splunk_TA_aws/local/
  when: aws.cloudtrail == "1"

- name: Copy new aws_account_ext.conf configuration
  template:
    src: aws_account_ext.conf.j2
    dest: /opt/splunk/etc/apps/Splunk_TA_aws/local/aws_account_ext.conf
  when: aws.cloudtrail == "1"

- name: Copy new inputs.conf configuration
  template:
    src: aws_inputs.conf.j2
    dest: /opt/splunk/etc/apps/Splunk_TA_aws/local/inputs.conf
  when: aws.cloudtrail == "1"