---

- name: Enable strong dotnet crypto
  win_regedit:
    key: "{{ item }}"
    value: SchUseStrongCrypto
    datatype: dword
    data: 1
  with_items:
    - "HKLM:\\SOFTWARE\\Microsoft\\.NetFramework\\v4.0.30319"
    - "HKLM:\\SOFTWARE\\Wow6432Node\\Microsoft\\.NetFramework\\v4.0.30319"

- name: Check installed providers
  win_shell: Get-PackageProvider -ListAvailable
  register: providers

- name: Install NuGet Provider
  win_shell: |
    Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
  when: providers.stdout is not search("NuGet")

- name: Install Atomic Red Team
  win_shell: |
    Set-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Internet Explorer\Main" -Name "DisableFirstRunCustomize" -Value 2
    IEX (IWR https://raw.githubusercontent.com/redcanaryco/invoke-atomicredteam/master/install-atomicredteam.ps1)
    Install-AtomicRedTeam -Force
    IEX (IWR 'https://raw.githubusercontent.com/redcanaryco/invoke-atomicredteam/master/install-atomicsfolder.ps1' -UseBasicParsing)
    Install-AtomicsFolder -Force -RepoOwner "{{ simulation.atomic_red_team_repo }}" -Branch "{{ simulation.atomic_red_team_branch }}"
  register: install_art

- name: copy default powershell profile
  win_copy:
    src: profile.ps1
    dest: C:\Windows\System32\WindowsPowerShell\v1.0\profile.ps1

- name: Download Latest PurpleSharp Binary
  win_shell: |
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls, [Net.SecurityProtocolType]::Tls11, [Net.SecurityProtocolType]::Tls12, [Net.SecurityProtocolType]::Ssl3
    [Net.ServicePointManager]::SecurityProtocol = 'Tls, Tls11, Tls12, Ssl3'
    If (-not (Test-Path c:\Tools\PurpleSharp)) { New-Item -Path c:\Tools\ -Name PurpleSharp -ItemType directory }
    $tag = (Invoke-WebRequest 'https://api.github.com/repos/mvelazc0/PurpleSharp/releases' -UseBasicParsing | ConvertFrom-Json)[0].tag_name
    $purplesharpDownloadUrl = 'https://github.com/mvelazc0/PurpleSharp/releases/download/' + $tag + '/PurpleSharp_x64.exe'
    If (-not (Test-Path c:\Tools\PurpleSharp\PurpleSharp.exe)) { Invoke-WebRequest -Uri $purplesharpDownloadUrl -OutFile c:\Tools\PurpleSharp\PurpleSharp.exe }

