---

- name: Install aptitude
  apt:
    name: aptitude
    state: latest
    update_cache: true

- name: Install required system packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: latest
    update_cache: true

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Update apt and install docker-ce
  apt:
    name: docker-ce
    state: latest
    update_cache: true

- name: Install Docker Module for Python
  pip:
    name: docker

- name: adding user splunk to docker group
  user:
    name: splunk
    groups: docker
    append: yes
  become: yes

- name: Create folder directory for configuration
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - /opt/splunk/etc/apps/mltk-container/local/

- name: copy docker.conf to splunk server
  copy:
    src: docker.conf
    dest: /opt/splunk/etc/apps/mltk-container/local/docker.conf
  notify: restart splunk

- name: pull docker containers
  become: true
  command: docker pull phdrieger/mltk-container-golden-image-cpu:3.9.0

- name: copy local.meta for mltk
  copy:
    src: mltk.local.meta
    dest: /opt/splunk/etc/apps//Splunk_ML_Toolkit/metadata/local.meta
  notify: restart splunk