- name: Create local folder directory
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - /opt/splunk/etc/apps/Splunk_SA_CIM/local/

- name: copy datamodels.conf to splunk server
  copy:
    src: datamodels.conf
    dest: /opt/splunk/etc/apps/Splunk_SA_CIM/local/datamodels.conf
  notify: restart splunk
