
- name: Create folder directory for web configuration
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - /opt/splunk/etc/apps/system/local/

- name: copy web.conf to splunk server
  copy:
    src: web.conf
    dest: /opt/splunk/etc/apps/system/local/web.conf
  notify: restart splunk
