---
# This playbook install the apps required in a server

- name: download splunk
  get_url:
    url: "{{ splunk_server.splunk_url }}"
    dest: /opt/splunk.tgz

- name: install splunk binary
  unarchive: remote_src=yes src=/opt/splunk.tgz dest=/opt/ creates=yes
  become: yes

- name: migrate to WiredTiger
  blockinfile:
    path: /opt/splunk/etc/system/local/server.conf
    insertafter: EOF
    create: yes
    block: |
      [kvstore]
      storageEngine=wiredTiger

- name: accept license and start splunk
  shell: /opt/splunk/bin/splunk start --accept-license --answer-yes --no-prompt --seed-passwd Pl3ase-k1Ll-me:p
  become: yes

- name: enable boot-start
  shell: /opt/splunk/bin/splunk enable boot-start

- name: restart splunk
  service:
    name: splunkd
    state: restarted