---

- name: Create folder directory for Azure TA
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - /opt/splunk/etc/apps/Splunk_TA_microsoft-cloudservices/local/
  when: azure.azure_logging == "1"

- name: Copy new mscs_azure_accounts.conf configuration
  template:
    src: mscs_azure_accounts.conf.j2
    dest: /opt/splunk/etc/apps/Splunk_TA_microsoft-cloudservices/local/mscs_azure_accounts.conf
  when: azure.azure_logging == "1"

- name: Copy new mscs_azure_audit_inputs.conf configuration
  template:
    src: mscs_azure_audit_inputs.conf.j2
    dest: /opt/splunk/etc/apps/Splunk_TA_microsoft-cloudservices/local/mscs_azure_audit_inputs.conf
  when: azure.azure_logging == "1"

- name: Copy new inputs.conf configuration
  template:
    src: inputs.conf.j2
    dest: /opt/splunk/etc/apps/Splunk_TA_microsoft-cloudservices/local/inputs.conf
  when: azure.azure_logging == "1"

- name: restart splunk
  service: name=splunk state=restarted
  become: yes
  when: azure.azure_logging == "1"