---

- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Install each and every of the dependencies that our Guacamole server will require to breath and live.
  apt:
    pkg:
      - gcc
      - vim
      - curl
      - wget
      - g++
      - libcairo2-dev
      - libjpeg-turbo8-dev
      - libpng-dev
      - libtool-bin
      - libossp-uuid-dev
      - libavcodec-dev
      - libavformat-dev
      - libavutil-dev
      - libswscale-dev
      - build-essential
      - libpango1.0-dev
      - libssh2-1-dev
      - libvncserver-dev
      - libtelnet-dev
      - libpulse-dev
      - libssl-dev
      - libvorbis-dev
      - libwebp-dev
      - openjdk-11-jdk

- name: Add FreeRDP2 repository key
  ansible.builtin.get_url:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x04E38CE134B239B9F38F82EE8A993C2521C5F0BA
    dest: /etc/apt/trusted.gpg.d/remmina-ppa-team.asc
  become: yes

- name: Add FreeRDP2 repository
  ansible.builtin.apt_repository:
    repo: 'ppa:remmina-ppa-team/remmina-next-daily'
    state: present
  become: yes

- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Install FreeRDP
  apt:
    pkg:
      - freerdp2-dev
      - freerdp2-x11