
- name: Create folder directory for deplyment client configuration
  win_file:
    path: C:\Program Files\SplunkUniversalForwarder\etc\apps\win_deploymentclient_app\local
    state: directory

- name: Copy a deploymentclient.conf using templating
  win_template:
    src: deploymentclient.conf.j2
    dest: C:\Program Files\SplunkUniversalForwarder\etc\apps\win_deploymentclient_app\local\deploymentclient.conf
