---

- name: Create ansible directories
  win_file:
    path: "{{ item }}"
    state: directory
  with_items:
    - 'c:\Program Files\ansible'
    - 'c:\ProgramData\ansible\log'

- include_tasks: windows-sysmon.yml
- include_tasks: windows-logging-registry.yml

- name: 'Reboot server'
  win_reboot:
