---
- name: Install GO [Caldera]
  become: true
  ansible.builtin.unarchive:
    src: "https://go.dev/dl/go{{ caldera_server.go_version }}.linux-amd64.tar.gz"
    dest: /usr/local
    remote_src: true
    owner: root
    group: root
