---
- name: Install UPX [Caldera]
  become: true
  ansible.builtin.unarchive:
    src: "https://github.com/upx/upx/releases/download/v{{ caldera_server.upx_version }}/upx-{{ caldera_server.upx_version }}-amd64_linux.tar.xz"
    dest: /usr/local
    remote_src: true
    owner: root
    group: root
