---

- name: Copy crowdstrike falcon agent 
  win_copy:
    src: "../../apps/{{ windows_servers.crowdstrike_windows_agent }}"
    dest: c:\temp\WindowsSensor.exe

- name: install crowdstrike falcon agent 
  win_command: 'C:\Temp\WindowsSensor.exe /install /quiet /norestart CID={{ general.crowdstrike_customer_ID }}'