- hosts: all
  gather_facts: False
  become: true
  vars:  
    hostname: splunk-server
    cloudtrail: "0"
    azure_logging: "0"
    kali_server: "0"
  roles:
    - linux_common
    - splunk_server
    - splunk_server_post
    - phantom_byo_splunk
    - cloudtrail_logs
    - azure_logging
    - carbon_black_cloud_logs
    - crowdstrike_falcon_logging
    - guacamole
    - cisco_secure_endpoint_logs
